-- Migration: Configure all 8 UAE Visa Types with verified fees, validity, stay period and processing times
-- 2026-09-08

delete from visa_types where country_slug in ('united-arab-emirates', 'uae') or slug in (
  '30-days-tourist-visa',
  '60-days-tourist-visa',
  '30-days-uae-visa',
  '60-days-uae-visa',
  'uae-30-days-tourist-visa',
  'uae-60-days-tourist-visa',
  'uae-48-hours-transit-visa',
  'uae-96-hours-transit-visa',
  'uae-14-days-tourist-visa',
  'uae-30-days-family-tourist-visa',
  'uae-30-days-tourist-visa-express',
  'uae-30-days-multiple-entry-visa'
);

insert into visa_types
(slug, name, country_slug, category, sub, price_aed, prices, days, processing_time_value, processing_time_unit, popular, active, sort_order, features, blurb)
values
(
  'uae-48-hours-transit-visa',
  '48 Hours Transit Visa',
  'united-arab-emirates',
  'Transit',
  'Single Entry',
  3499,
  jsonb_build_object('INR', 3499),
  2,
  5,
  'working days',
  false,
  true,
  10,
  array['Stay up to 2 days (48 Hours)', 'Validity: 30 Days', 'Single Entry', 'Processing: Upto 5 Days']::text[],
  '48 Hours Transit Visa for UAE. Single entry valid for 30 days with up to 5 days processing.'
),
(
  'uae-30-days-tourist-visa',
  '30 Days Tourist Visa',
  'united-arab-emirates',
  'Tourist',
  'Single Entry',
  7600,
  jsonb_build_object('INR', 7600),
  30,
  5,
  'working days',
  true,
  true,
  20,
  array['Stay up to 30 Days', 'Validity: 58 Days', 'Single Entry', 'Processing: Upto 5 Days']::text[],
  '30 Days Tourist Visa for UAE. Single entry valid for 58 days with up to 5 days processing.'
),
(
  'uae-30-days-family-tourist-visa',
  '30 Days Family Tourist Visa (Includes 2 Adults + 1 Child)',
  'united-arab-emirates',
  'Tourist',
  'Single Entry',
  19999,
  jsonb_build_object('INR', 19999),
  30,
  5,
  'working days',
  false,
  true,
  30,
  array['Includes 2 Adults + 1 Child', 'Stay up to 30 Days', 'Validity: 58 Days', 'Single Entry', 'Processing: Upto 5 Days']::text[],
  '30 Days Family Tourist Visa for UAE (Includes 2 Adults + 1 Child). Single entry valid for 58 days.'
),
(
  'uae-96-hours-transit-visa',
  '96 Hours Transit Visa',
  'united-arab-emirates',
  'Transit',
  'Single Entry',
  5299,
  jsonb_build_object('INR', 5299),
  4,
  5,
  'working days',
  false,
  true,
  40,
  array['Stay up to 4 days (96 Hours)', 'Validity: 30 Days', 'Single Entry', 'Processing: Upto 5 Days']::text[],
  '96 Hours Transit Visa for UAE. Single entry valid for 30 days with up to 5 days processing.'
),
(
  'uae-14-days-tourist-visa',
  '14 Days Tourist Visa',
  'united-arab-emirates',
  'Tourist',
  'Single Entry',
  7699,
  jsonb_build_object('INR', 7699),
  14,
  5,
  'working days',
  false,
  true,
  50,
  array['Stay up to 14 Days', 'Validity: 58 Days', 'Single Entry', 'Processing: Upto 5 Days']::text[],
  '14 Days Tourist Visa for UAE. Single entry valid for 58 days with up to 5 days processing.'
),
(
  'uae-30-days-tourist-visa-express',
  '30 Days Tourist Visa (Express)',
  'united-arab-emirates',
  'Tourist',
  'Single Entry',
  8999,
  jsonb_build_object('INR', 8999),
  30,
  48,
  'hours',
  false,
  true,
  60,
  array['Stay up to 30 Days', 'Validity: 58 Days', 'Single Entry', 'Express Processing: Upto 48 Hours']::text[],
  'Express 30 Days Tourist Visa for UAE. Fast processing within 48 hours.'
),
(
  'uae-60-days-tourist-visa',
  '60 Days Tourist Visa',
  'united-arab-emirates',
  'Tourist',
  'Single Entry',
  10800,
  jsonb_build_object('INR', 10800),
  60,
  5,
  'working days',
  false,
  true,
  70,
  array['Stay up to 60 Days', 'Validity: 58 Days', 'Single Entry', 'Processing: Upto 5 Days']::text[],
  '60 Days Tourist Visa for UAE. Single entry valid for 58 days with up to 5 days processing.'
),
(
  'uae-30-days-multiple-entry-visa',
  '30 Days Multiple Entry Tourist Visa',
  'united-arab-emirates',
  'Tourist',
  'Multiple Entry',
  17999,
  jsonb_build_object('INR', 17999),
  30,
  5,
  'working days',
  false,
  true,
  80,
  array['Stay up to 30 Days', 'Validity: 58 Days', 'Multiple Entry', 'Processing: Upto 5 Days']::text[],
  '30 Days Multiple Entry Tourist Visa for UAE. Multiple entries within 58 days validity.'
);