-- =========================================================================
-- Visa Doo — Major International Events Update
-- 15 Countries: Morocco, Qatar, Sri Lanka, Philippines, UAE, Bahrain, Vietnam, Thailand, Egypt, Russia, Oman, Indonesia, Saudi Arabia, Kenya, Azerbaijan
-- Date: 2026-09-12
-- Execute in Supabase SQL Editor.
-- =========================================================================

-- 1. Remove all old events
delete from public.events;

-- 2. Insert verified events for the 15 countries
insert into public.events (
  slug,
  name,
  country_slug,
  category,
  event_date,
  end_date,
  city,
  image_url,
  image_alt,
  blurb,
  seo_title,
  seo_description,
  featured,
  sort_order,
  active,
  created_at,
  updated_at
) values
-- Morocco
(
  'moga-festival-2026',
  'Moga Festival 2026',
  'morocco',
  'Music & Culture',
  '2026-09-30',
  '2026-10-04',
  'Essaouira, Morocco',
  'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
  'Moga Festival in Essaouira Morocco',
  'A premier electronic music and digital arts festival blending traditional Gnawa rhythms with modern electronic sounds in coastal Essaouira.',
  'Moga Festival 2026 Morocco Visa | Visa Doo',
  'Attend Moga Festival 2026 in Essaouira. Fast Morocco tourist eVisa processing with Visa Doo.',
  true,
  1,
  true,
  now(),
  now()
),
(
  'marrakech-film-festival-2026',
  'Marrakech International Film Festival 2026',
  'morocco',
  'Festivals',
  '2026-11-20',
  '2026-11-28',
  'Marrakech, Morocco',
  'https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=1200&q=80',
  'Marrakech International Film Festival in Morocco',
  'One of the most prestigious film gatherings in Africa and the Arab world, held amidst the historic palaces of Marrakech.',
  'Marrakech Film Festival 2026 Morocco Visa | Visa Doo',
  'Plan your visit to Marrakech International Film Festival 2026. Get your Morocco eVisa with Visa Doo.',
  true,
  2,
  true,
  now(),
  now()
),
(
  'visa-for-music-2026',
  'Visa For Music 2026',
  'morocco',
  'Music & Culture',
  '2026-11-18',
  '2026-11-21',
  'Rabat, Morocco',
  'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
  'Visa For Music festival in Rabat Morocco',
  'The premier international music market and festival for Africa and the Middle East, bringing together global musicians in Rabat.',
  'Visa For Music Rabat 2026 Morocco Visa | Visa Doo',
  'Experience Visa For Music 2026 in Rabat. 100% online Morocco eVisa application on Visa Doo.',
  false,
  3,
  true,
  now(),
  now()
),

-- Qatar
(
  'doha-jewellery-watches-exhibition-2026',
  'Doha Jewellery & Watches Exhibition 2026',
  'qatar',
  'Shopping',
  '2026-09-28',
  '2026-10-03',
  'Doha, Qatar',
  'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=80',
  'Doha Jewellery & Watches Exhibition in Qatar',
  'A high-profile luxury showcase featuring world-renowned jewelry brands, limited-edition horology, and bespoke craftsmanship.',
  'Doha Jewellery & Watches 2026 Qatar Visa | Visa Doo',
  'Visit DJWE 2026 in Doha. Fast, approved Qatar tourist visa processing with Visa Doo.',
  true,
  4,
  true,
  now(),
  now()
),
(
  'qatar-classic-squash-2026',
  'Qatar Classic Squash 2026',
  'qatar',
  'Sports',
  '2026-09-12',
  '2026-09-18',
  'Doha, Qatar',
  'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&w=1200&q=80',
  'Qatar Classic Squash championship in Doha',
  'World elite squash tournament hosted at the Khalifa International Tennis and Squash Complex in Doha.',
  'Qatar Classic Squash 2026 Visa | Visa Doo',
  'Travel to Doha for the Qatar Classic Squash 2026 with official Qatar visa services from Visa Doo.',
  false,
  5,
  true,
  now(),
  now()
),

-- Sri Lanka
(
  'deepavali-festival-sri-lanka-2026',
  'Deepavali Festival 2026',
  'srilanka',
  'Festivals',
  '2026-11-08',
  '2026-11-08',
  'Colombo, Sri Lanka',
  'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=80',
  'Deepavali Festival in Sri Lanka',
  'The radiant Festival of Lights celebrated with oil lamps, vibrant kolams, and joyful community festivities across temples.',
  'Deepavali Sri Lanka 2026 Visa | Visa Doo',
  'Celebrate Deepavali in Sri Lanka. Instant 24-hour Sri Lanka ETA processing with Visa Doo.',
  true,
  6,
  true,
  now(),
  now()
),
(
  'unduvap-full-moon-poya-2026',
  'Unduvap Full Moon Poya 2026',
  'srilanka',
  'Holidays',
  '2026-12-23',
  '2026-12-23',
  'Anuradhapura & Colombo, Sri Lanka',
  'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
  'Unduvap Full Moon Poya in Sri Lanka',
  'A sacred Buddhist festival commemorating the arrival of Sanghamitta Theri and the planting of the sacred Jaya Sri Maha Bodhi sapling.',
  'Unduvap Poya 2026 Sri Lanka Visa | Visa Doo',
  'Visit Sri Lanka for Unduvap Full Moon Poya 2026. Apply for your tourist visa on Visa Doo.',
  false,
  7,
  true,
  now(),
  now()
),

-- Philippines
(
  'penafrancia-festival-2026',
  'Peñafrancia Festival 2026',
  'philippines',
  'Festivals',
  '2026-09-18',
  '2026-09-20',
  'Naga City, Philippines',
  'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1200&q=80',
  'Peñafrancia Festival fluvial procession in Naga City',
  'The largest Marian festival in Asia featuring a majestic fluvial procession along the Naga River and colorful cultural spectacles.',
  'Peñafrancia Festival 2026 Philippines Visa | Visa Doo',
  'Attend the Peñafrancia Festival 2026 in Naga City with fast Philippines visa assistance from Visa Doo.',
  false,
  8,
  true,
  now(),
  now()
),
(
  'masskara-festival-2026',
  'MassKara Festival 2026',
  'philippines',
  'Festivals',
  '2026-10-16',
  '2026-10-19',
  'Bacolod, Philippines',
  'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1200&q=80',
  'MassKara Festival colorful smiling masks in Bacolod',
  'The City of Smiles celebration famous for energetic street dance competitions, elaborate smiling masks, and dazzling carnival costumes.',
  'MassKara Festival Bacolod 2026 Visa | Visa Doo',
  'Join the MassKara Festival in Bacolod. Apply for your Philippines visa on Visa Doo.',
  true,
  9,
  true,
  now(),
  now()
),
(
  'higantes-festival-2026',
  'Higantes Festival 2026',
  'philippines',
  'Festivals',
  '2026-11-22',
  '2026-11-23',
  'Angono, Rizal, Philippines',
  'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1200&q=80',
  'Higantes Festival giant paper-mache puppets in Angono',
  'Parade of towering giant paper-mâché puppets celebrating the feast of Saint Clement in the art capital of the Philippines.',
  'Higantes Festival 2026 Philippines Visa | Visa Doo',
  'Experience the giant puppets of Higantes Festival 2026. Secure your Philippines visa with Visa Doo.',
  false,
  10,
  true,
  now(),
  now()
),

-- UAE
(
  'abu-dhabi-international-book-fair-2026',
  'Abu Dhabi International Book Fair 2026',
  'united-arab-emirates',
  'Global Events',
  '2026-09-13',
  '2026-09-18',
  'Abu Dhabi, UAE',
  'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80',
  'Abu Dhabi International Book Fair at ADNEC',
  'Leading literary and publishing fair gathering regional authors, intellectual leaders, and global publishers at ADNEC.',
  'Abu Dhabi Book Fair 2026 UAE Visa | Visa Doo',
  'Visit ADIBF 2026 in Abu Dhabi. Get your UAE tourist visa in 24 hours with Visa Doo.',
  false,
  11,
  true,
  now(),
  now()
),
(
  'f1-abu-dhabi-grand-prix-2026',
  'Abu Dhabi F1 Grand Prix 2026',
  'united-arab-emirates',
  'Sports',
  '2026-12-04',
  '2026-12-06',
  'Yas Island, Abu Dhabi, UAE',
  'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
  'Yas Marina Circuit Abu Dhabi F1 Grand Prix sunset',
  'The iconic twilight finale of the Formula 1 World Championship at Yas Marina Circuit, coupled with A-list international concerts.',
  'Abu Dhabi F1 Grand Prix 2026 UAE Visa | Visa Doo',
  'Get your UAE visa for the 2026 Abu Dhabi Grand Prix at Yas Marina with Visa Doo fast processing.',
  true,
  12,
  true,
  now(),
  now()
),
(
  'gitex-global-2026',
  'GITEX Global 2026',
  'united-arab-emirates',
  'Business',
  '2026-12-08',
  '2026-12-11',
  'Dubai, UAE',
  'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
  'GITEX Global tech exhibition at Dubai World Trade Centre',
  'The world''s largest enterprise tech and AI exhibition bringing together global innovators, founders and tech giants at Dubai World Trade Centre.',
  'GITEX Global 2026 Dubai UAE Visa | Visa Doo',
  'Fast UAE visa approval for GITEX Global Dubai 2026. 100% online application with Visa Doo.',
  true,
  13,
  true,
  now(),
  now()
),

-- Bahrain
(
  'jewellery-arabia-2026',
  'Jewellery Arabia 2026',
  'bahrain',
  'Shopping',
  '2026-11-24',
  '2026-11-28',
  'Sakhir, Bahrain',
  'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80',
  'Jewellery Arabia luxury exhibition in Bahrain',
  'The Middle East''s premier jewelry and watch show at Exhibition World Bahrain, showcasing world-class luxury houses and master jewelers.',
  'Jewellery Arabia 2026 Bahrain Visa | Visa Doo',
  'Visit Jewellery Arabia in Bahrain. Express eVisa processing and document guidance with Visa Doo.',
  true,
  14,
  true,
  now(),
  now()
),
(
  'royal-bahrain-concours-2026',
  'Royal Bahrain Concours 2026',
  'bahrain',
  'Global Events',
  '2026-11-06',
  '2026-11-07',
  'Manama, Bahrain',
  'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
  'Royal Bahrain Concours classic luxury cars in Manama',
  'An elite automotive elegance competition displaying the world''s most exquisite classic, vintage, and bespoke hypercars.',
  'Royal Bahrain Concours 2026 Visa | Visa Doo',
  'Travel to Bahrain for Royal Concours 2026. Fast tourist visa on Visa Doo.',
  false,
  15,
  true,
  now(),
  now()
),

-- Vietnam
(
  'central-highlands-gong-culture-festival-2026',
  'Central Highlands Gong Culture Festival 2026',
  'vietnam',
  'Festivals',
  '2026-10-10',
  '2026-10-14',
  'Pleiku, Gia Lai, Vietnam',
  'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80',
  'Central Highlands Gong Culture Festival in Vietnam',
  'UNESCO Intangible Cultural Heritage celebration honoring the sacred gong melodies and spiritual folklore of ethnic minorities.',
  'Central Highlands Gong Festival Vietnam 2026 Visa | Visa Doo',
  'Explore the cultural heritage of Vietnam. Apply for your Vietnam eVisa online with Visa Doo.',
  false,
  16,
  true,
  now(),
  now()
),
(
  'hanoi-craft-village-gastronomy-festival-2026',
  'Hanoi Craft Village & Gastronomy Festival 2026',
  'vietnam',
  'Festivals',
  '2026-10-16',
  '2026-10-20',
  'Hanoi, Vietnam',
  'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
  'Hanoi Craft Village & Gastronomy Festival in Vietnam',
  'Celebration of traditional craft artistry, street gastronomy, pottery, and culinary heritage in historic Hanoi.',
  'Hanoi Craft & Food Festival 2026 Vietnam Visa | Visa Doo',
  'Taste Hanoi''s world-famous cuisine. Instant Vietnam eVisa approval with Visa Doo.',
  true,
  17,
  true,
  now(),
  now()
),
(
  'kate-festival-2026',
  'Kate Festival 2026',
  'vietnam',
  'Festivals',
  '2026-10-24',
  '2026-10-26',
  'Ninh Thuan, Vietnam',
  'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=80',
  'Kate Festival Cham towers in Ninh Thuan Vietnam',
  'The most significant ethnic Cham festival honoring ancient ancestors, kings, and traditional deities at Po Klong Garai towers.',
  'Kate Festival Vietnam 2026 Visa | Visa Doo',
  'Experience Vietnam''s Cham cultural tradition. Get your Vietnam tourist visa on Visa Doo.',
  false,
  18,
  true,
  now(),
  now()
),

-- Thailand
(
  'loy-krathong-festival-2026',
  'Loy Krathong Festival 2026',
  'thailand',
  'Festivals',
  '2026-11-15',
  '2026-11-24',
  'Chiang Mai & Bangkok, Thailand',
  'https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=1200&q=80',
  'Loy Krathong sky lanterns in Chiang Mai Thailand',
  'Thailand''s enchanting Festival of Lights where thousands of glowing lotus-shaped baskets float along rivers and lanterns fill the night sky.',
  'Loy Krathong 2026 Thailand Visa | Visa Doo',
  'Experience the magic of Loy Krathong 2026. Apply for your Thailand eVisa with Visa Doo.',
  true,
  19,
  true,
  now(),
  now()
),
(
  'tomorrowland-thailand-2026',
  'Tomorrowland Thailand 2026',
  'thailand',
  'Music & Culture',
  '2026-12-11',
  '2026-12-13',
  'Pattaya, Thailand',
  'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80',
  'Tomorrowland Thailand massive music festival stage',
  'The legendary global EDM music festival makes its historic debut in Southeast Asia with breathtaking stage design and top international DJs.',
  'Tomorrowland Thailand 2026 Visa | Visa Doo',
  'Attend Tomorrowland Thailand 2026 in Pattaya. Quick Thailand eVisa processing on Visa Doo.',
  true,
  20,
  true,
  now(),
  now()
),
(
  'bangkok-art-biennale-2026',
  'Bangkok Art Biennale 2026–27',
  'thailand',
  'Music & Culture',
  '2026-10-24',
  '2027-02-28',
  'Bangkok, Thailand',
  'https://images.unsplash.com/photo-1563492065599-3520f775eeed?auto=format&fit=crop&w=1200&q=80',
  'Bangkok Art Biennale contemporary installation along Chao Phraya River',
  'Vibrant contemporary art exhibitions across Bangkok''s ancient temples, heritage sites, and premier cultural centers along the Chao Phraya River.',
  'Bangkok Art Biennale 2026-27 Visa | Visa Doo',
  'Discover contemporary art in Bangkok. Apply for your Thailand visa with Visa Doo.',
  false,
  21,
  true,
  now(),
  now()
),

-- Egypt
(
  'cairo-international-film-festival-2026',
  'Cairo International Film Festival 2026',
  'egypt',
  'Festivals',
  '2026-11-18',
  '2026-11-27',
  'Cairo, Egypt',
  'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
  'Cairo International Film Festival Opera House',
  'The oldest internationally accredited film festival in the Arab world and Africa, hosted at the Cairo Opera House.',
  'Cairo Film Festival 2026 Egypt Visa | Visa Doo',
  'Attend CIFF 2026 in Cairo. Fast, reliable Egypt tourist visa application with Visa Doo.',
  true,
  22,
  true,
  now(),
  now()
),
(
  'cairo-international-jazz-festival-2026',
  'Cairo International Jazz Festival 2026',
  'egypt',
  'Music & Culture',
  '2026-10-29',
  '2026-11-05',
  'Cairo, Egypt',
  'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1200&q=80',
  'Cairo International Jazz Festival live concert',
  'Annual celebration uniting world-class international jazz virtuosos with celebrated Egyptian musicians across historic venues.',
  'Cairo Jazz Festival 2026 Egypt Visa | Visa Doo',
  'Enjoy live jazz in Cairo. Apply for your Egypt visa online on Visa Doo.',
  false,
  23,
  true,
  now(),
  now()
),

-- Russia
(
  'pir-expo-moscow-2026',
  'PIR Expo Moscow 2026',
  'russia',
  'Business',
  '2026-10-19',
  '2026-10-22',
  'Moscow, Russia',
  'https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=1200&q=80',
  'PIR Expo Moscow Crocus Expo center',
  'The largest professional exhibition for the hospitality and restaurant industry across Russia and the CIS region at Crocus Expo.',
  'PIR Expo Moscow 2026 Russia Visa | Visa Doo',
  'Attend PIR Expo Moscow 2026. Expert Russia tourist & business visa processing on Visa Doo.',
  true,
  24,
  true,
  now(),
  now()
),
(
  'kazan-digital-week-2026',
  'Kazan Digital Week 2026',
  'russia',
  'Business',
  '2026-10-21',
  '2026-10-24',
  'Kazan, Russia',
  'https://images.unsplash.com/photo-1520106212299-d99c443e4568?auto=format&fit=crop&w=1200&q=80',
  'Kazan Digital Week tech forum in Russia',
  'Major international forum on digital technologies, intelligent transport, fintech, and cybersecurity held in tech-forward Kazan.',
  'Kazan Digital Week 2026 Russia Visa | Visa Doo',
  'Travel to Kazan Digital Week 2026 with guided Russia visa assistance from Visa Doo.',
  false,
  25,
  true,
  now(),
  now()
),

-- Oman
(
  'muscat-art-2026',
  'Muscat Art 2026',
  'oman',
  'Music & Culture',
  '2026-10-28',
  '2026-10-30',
  'Muscat, Oman',
  'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?auto=format&fit=crop&w=1200&q=80',
  'Muscat Art modern exhibition at OCEC Oman',
  'Leading regional contemporary art fair at Oman Convention & Exhibition Centre bringing together Middle Eastern galleries and international artists.',
  'Muscat Art 2026 Oman Visa | Visa Doo',
  'Experience Muscat Art 2026. Apply for your Oman tourist visa online with Visa Doo.',
  true,
  26,
  true,
  now(),
  now()
),
(
  'oman-agrofood-2026',
  'Oman AgroFood 2026',
  'oman',
  'Business',
  '2026-12-01',
  '2026-12-03',
  'Muscat, Oman',
  'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
  'Oman AgroFood trade exhibition in Muscat',
  'International trade exhibition for agriculture, food processing, fisheries, and sustainable culinary trade at OCEC Muscat.',
  'Oman AgroFood 2026 Visa | Visa Doo',
  'Attend Oman AgroFood 2026 in Muscat with fast Oman eVisa approval on Visa Doo.',
  false,
  27,
  true,
  now(),
  now()
),

-- Indonesia
(
  'motogp-indonesia-mandalika-2026',
  'MotoGP Indonesia – Mandalika 2026',
  'indonesia',
  'Sports',
  '2026-10-09',
  '2026-10-11',
  'Mandalika, Lombok, Indonesia',
  'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
  'MotoGP Indonesia Mandalika oceanfront circuit',
  'Thrilling premier motorcycle racing action on the picturesque oceanfront Mandalika International Street Circuit in Lombok.',
  'MotoGP Indonesia Mandalika 2026 Visa | Visa Doo',
  'Get your Indonesia tourist visa for MotoGP Mandalika 2026 with Visa Doo.',
  true,
  28,
  true,
  now(),
  now()
),
(
  'ubud-writers-readers-festival-2026',
  'Ubud Writers & Readers Festival 2026',
  'indonesia',
  'Music & Culture',
  '2026-10-21',
  '2026-10-25',
  'Ubud, Bali, Indonesia',
  'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
  'Ubud Writers & Readers Festival in Bali Indonesia',
  'Southeast Asia''s celebrated literary and arts festival nestled among Bali''s tropical rainforests and cultural landmarks.',
  'Ubud Writers Festival 2026 Bali Visa | Visa Doo',
  'Travel to Ubud Writers Festival 2026 in Bali. Fast Indonesia visa application on Visa Doo.',
  false,
  29,
  true,
  now(),
  now()
),

-- Saudi Arabia
(
  'saudi-national-day-2026',
  'Saudi National Day 2026',
  'saudi-arabia',
  'Festivals',
  '2026-09-23',
  '2026-09-23',
  'Riyadh & Jeddah, Saudi Arabia',
  'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?auto=format&fit=crop&w=1200&q=80',
  'Saudi National Day fireworks celebration in Riyadh',
  'Nationwide celebration featuring spectacular air shows, dazzling green fireworks, military parades, and concerts across the Kingdom.',
  'Saudi National Day 2026 Visa | Visa Doo',
  'Celebrate Saudi National Day 2026. Instant Saudi Arabia tourist eVisa with Visa Doo.',
  true,
  30,
  true,
  now(),
  now()
),
(
  'formula-e-jeddah-2026',
  'Formula E Jeddah 2026',
  'saudi-arabia',
  'Sports',
  '2026-12-18',
  '2026-12-19',
  'Jeddah, Saudi Arabia',
  'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
  'Formula E Jeddah electric street racing in Saudi Arabia',
  'All-electric street racing championship along the Red Sea coastline on the world''s fastest street circuit in Jeddah.',
  'Formula E Jeddah 2026 Saudi Visa | Visa Doo',
  'Experience Formula E in Jeddah 2026. Apply for your Saudi Arabia visa on Visa Doo.',
  false,
  31,
  true,
  now(),
  now()
),

-- Kenya
(
  'nairobi-international-trade-fair-2026',
  'Nairobi International Trade Fair 2026',
  'kenya',
  'Business',
  '2026-10-05',
  '2026-10-11',
  'Nairobi, Kenya',
  'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?auto=format&fit=crop&w=1200&q=80',
  'Nairobi International Trade Fair in Kenya',
  'East Africa''s premier commercial and agricultural trade expo at Jamhuri Park, showcasing regional business and agro-innovation.',
  'Nairobi Trade Fair 2026 Kenya Visa | Visa Doo',
  'Visit Nairobi International Trade Fair 2026 with Kenya eVisa / ETA services from Visa Doo.',
  true,
  32,
  true,
  now(),
  now()
),
(
  'nairobi-festive-season-christmas-2026',
  'Christmas / Nairobi Festive Season 2026',
  'kenya',
  'Seasonal',
  '2026-12-20',
  '2026-12-28',
  'Nairobi & Coast, Kenya',
  'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
  'Kenyan safari festive holiday season sunset',
  'Magical festive holiday season combining vibrant Nairobi celebrations, safari national park excursions, and coastal beach getaways.',
  'Christmas in Kenya 2026 ETA Visa | Visa Doo',
  'Spend Christmas and festive holidays in Kenya. 100% online Kenya ETA processing with Visa Doo.',
  false,
  33,
  true,
  now(),
  now()
),

-- Azerbaijan
(
  'azerbaijan-f1-grand-prix-2026',
  'Azerbaijan F1 Grand Prix 2026',
  'azerbaijan',
  'Sports',
  '2026-09-24',
  '2026-09-26',
  'Baku, Azerbaijan',
  'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
  'Formula 1 Azerbaijan Grand Prix on Baku City Circuit',
  'High-speed thrills on the historic Baku City Circuit winding past UNESCO Old City walls and modern Flame Towers.',
  'Azerbaijan F1 Grand Prix 2026 Visa | Visa Doo',
  'Get your official Azerbaijan eVisa in hours for the Formula 1 Baku Grand Prix 2026 with Visa Doo.',
  true,
  34,
  true,
  now(),
  now()
),
(
  'baku-international-arts-festival-2026',
  'Baku International Arts Festival 2026',
  'azerbaijan',
  'Music & Culture',
  '2026-10-28',
  '2026-11-08',
  'Baku, Azerbaijan',
  'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?auto=format&fit=crop&w=1200&q=80',
  'Baku International Arts Festival in Azerbaijan',
  'A grand cross-cultural festival featuring symphonic performances, theater productions, carpet weaving masterclasses, and contemporary art.',
  'Baku Arts Festival 2026 Azerbaijan Visa | Visa Doo',
  'Travel to Baku International Arts Festival 2026. Apply for your ASAN eVisa on Visa Doo.',
  false,
  35,
  true,
  now(),
  now()
),
(
  'gastrofest-baku-2026',
  'GastroFest Baku 2026',
  'azerbaijan',
  'Festivals',
  '2026-10-16',
  '2026-10-18',
  'Baku, Azerbaijan',
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
  'GastroFest Baku culinary celebration in Azerbaijan',
  'Celebration of Caspian flavors, traditional Azerbaijani kebabs, plov, dolma, and international culinary masterclasses by renowned chefs.',
  'GastroFest Baku 2026 Azerbaijan Visa | Visa Doo',
  'Taste the authentic culinary heritage of Azerbaijan. Fast ASAN eVisa processing on Visa Doo.',
  false,
  36,
  true,
  now(),
  now()
);
